"""
GuardPay AI — mTLS Bank/PSP Fraud Alert Service
PROMPT 11: send_alert() over mTLS with 3-attempt exponential-backoff retries

Payload to bank (per playbook):
  { transaction_id, risk_score, contributing_factors,
    beneficiary_upi_id, amount, timestamp, evidence_bundle_id }

Retry logic: 3 attempts, exponential backoff (1s → 2s → 4s)
mTLS: self-signed cert for demo (certs/server.crt + certs/client.crt/key)

Author: Shanteshwar (Backend Lead)
"""

import asyncio
import logging
import json
from datetime import datetime, timezone
from typing import Optional, List
from pathlib import Path

import httpx

from backend.core.config import settings

logger = logging.getLogger(__name__)

# mTLS cert paths (self-signed for demo — generated by scripts/gen_certs.py)
CERTS_DIR = Path("certs")
CLIENT_CERT = CERTS_DIR / "client.crt"
CLIENT_KEY = CERTS_DIR / "client.key"
CA_CERT = CERTS_DIR / "ca.crt"


def _build_alert_payload(
    transaction_id: str,
    risk_score: float,
    contributing_factors: List[str],
    beneficiary_upi_id: str,
    amount: float,
    evidence_bundle_id: Optional[str],
) -> dict:
    return {
        "transaction_id": transaction_id,
        "risk_score": risk_score,
        "contributing_factors": contributing_factors,
        "beneficiary_upi_id": beneficiary_upi_id,
        "amount_inr": amount,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "evidence_bundle_id": evidence_bundle_id,
        "source": "guardpay-ai/v1.0",
    }


async def send_alert(
    transaction_id: str,
    risk_score: float,
    contributing_factors: List[str],
    beneficiary_upi_id: str,
    amount: float,
    evidence_bundle_id: Optional[str] = None,
    max_retries: int = 3,
) -> bool:
    """
    Sends fraud alert to bank/PSP endpoint with mTLS and exponential-backoff retry.

    Backoff is 2**(attempt-1) seconds and only ever happens BETWEEN attempts, so
    with the default max_retries=3 the schedule is:
        attempt 1 → wait 1s → attempt 2 → wait 2s → attempt 3 → (no wait, give up)
    The playbook lists the delays as "1s, 2s, 4s"; the 4s delay only occurs at
    max_retries=4, since waiting after the final attempt would just add latency
    before returning failure. Raise max_retries to 4 if that delay is wanted.

    Returns True if alert delivered, False if all attempts are exhausted.
    """
    payload = _build_alert_payload(
        transaction_id, risk_score, contributing_factors,
        beneficiary_upi_id, amount, evidence_bundle_id
    )

    endpoint = settings.BANK_ALERT_ENDPOINT

    # Determine mTLS config
    use_mtls = CLIENT_CERT.exists() and CLIENT_KEY.exists() and CA_CERT.exists()
    if not use_mtls:
        logger.warning(
            "[BankAlert] mTLS certs not found — sending over plain HTTP (demo mode). "
            "Run: python scripts/gen_certs.py to generate self-signed certs."
        )

    for attempt in range(1, max_retries + 1):
        try:
            if use_mtls:
                client = httpx.AsyncClient(
                    cert=(str(CLIENT_CERT), str(CLIENT_KEY)),
                    verify=str(CA_CERT),
                    timeout=5.0,
                )
            else:
                # verify stays True: disabling TLS verification to make a demo work
                # would silently accept any certificate if BANK_ALERT_ENDPOINT were
                # ever pointed at a real https PSP. Plain-http demo endpoints ignore it.
                client = httpx.AsyncClient(timeout=5.0)

            async with client:
                response = await client.post(
                    endpoint,
                    json=payload,
                    headers={"Content-Type": "application/json", "X-GuardPay-Version": "1.0"},
                )

            if response.status_code in (200, 201, 202):
                logger.info(
                    f"[BankAlert] SUCCESS attempt={attempt} "
                    f"txn={transaction_id} status={response.status_code}"
                )
                return True
            else:
                logger.warning(
                    f"[BankAlert] Non-2xx attempt={attempt}/{max_retries} "
                    f"status={response.status_code} body={response.text[:200]}"
                )

        except httpx.ConnectError:
            logger.warning(
                f"[BankAlert] Connection refused attempt={attempt}/{max_retries} "
                f"endpoint={endpoint} — is mock bank server running? (python scripts/mock_bank_server.py)"
            )
        except Exception as e:
            logger.error(f"[BankAlert] Unexpected error attempt={attempt}/{max_retries}: {e}")

        # Exponential backoff: 1s, 2s, 4s
        if attempt < max_retries:
            wait = 2 ** (attempt - 1)   # 1, 2, 4
            logger.info(f"[BankAlert] Retrying in {wait}s...")
            await asyncio.sleep(wait)

    logger.error(
        f"[BankAlert] FAILED after {max_retries} attempts — "
        f"txn={transaction_id} endpoint={endpoint}"
    )
    return False
