"""
coercion_engine.py — Coercion NLP Classification Engine
GuardPay AI · AI/ML Module (Jatin)

Two-path architecture per the playbook:
  1. Fast path  — TF-IDF lexicon match (< 5 ms, no API needed)
  2. Slow path  — Llama 3 via Groq API (escalated on uncertain TF-IDF score)

Contract:
    classify(text: str) -> {'label': 'COERCIVE'|'BENIGN', 'score': float, 'matched_phrases': list}

Async-safe via asyncio.to_thread for Groq calls.

Commit:
    feat(coercion): build TF-IDF coercion lexicon with 500 multilingual phrases
    feat(coercion): integrate Groq API Llama 3 coercion classifier
"""

from __future__ import annotations

import asyncio
import json
import os
import time
from pathlib import Path

import numpy as np

# ── Constants ──────────────────────────────────────────────────────────────────
TFIDF_THRESHOLD_COERCIVE = 0.35    # Above → COERCIVE
TFIDF_THRESHOLD_UNCERTAIN = 0.15   # Between → escalate to Groq
GROQ_MODEL = "llama3-8b-8192"
MAX_GROQ_RETRIES = 3

LEXICON_PATH = Path(__file__).parent.parent / "data" / "mock" / "coercion_lexicon" / "phrases.json"

# ── Coercion Lexicon ───────────────────────────────────────────────────────────

# 500 multilingual scam/coercion phrases across EN / HI / MR / TA
# Stored externally as JSON (generated by _build_lexicon) and loaded at startup
BUILTIN_PHRASES = {
    # ─ English ──────────────────────────────────────────────────────────────
    "en": [
        # Arrest / legal threat
        "you are under digital arrest", "cbi officer speaking", "ed officer",
        "your account is frozen", "warrant issued against you", "fir registered",
        "you will be arrested", "legal action will be taken", "court summons",
        "money laundering case", "drug trafficking case", "your aadhaar is misused",
        "interpol notice", "cybercrime investigation", "you must pay now",
        "transfer money immediately", "pay or be arrested", "do not tell anyone",
        "keep this call secret", "do not hang up", "stay on the line",
        "your pan card is blocked", "illegal transaction detected",
        "national security breach", "terrorist funding linked to you",
        "send money to clear your name", "this is your last chance",
        "video kyc verification required urgently", "your sim will be blocked",
        "rbi compliance notice", "sebi investigation", "customs department",
        "narcotics control bureau", "enforcement directorate", "high court order",
        "do not inform family", "case will be closed after payment",
        "immediate transfer required", "upi transfer to safe account",
        "government escrow account", "secure your funds now",
        # Urgency / pressure
        "time is running out", "urgent action required", "within 30 minutes",
        "within one hour", "before midnight", "last warning",
        "final notice", "do not delay", "act immediately",
        # Impersonation
        "i am calling from rbi", "supreme court order", "ministry of home affairs",
        "trai is blocking your number", "airtel legal department",
        "google legal team", "amazon fraud team", "sbi fraud department",
        "hdfc bank security", "icici bank compliance",
    ],
    # ─ Hindi ────────────────────────────────────────────────────────────────
    "hi": [
        "aapke upar arrest warrant hai", "cbi office se bol rahe hain",
        "aapka account band ho jayega", "abhi paisa transfer karo",
        "aapka aadhar card misuse hua hai", "police aa rahi hai",
        "ek ghante mein payment karo", "court ka order hai",
        "kisi ko mat batana", "call mat kato", "narcotics case mein naam aaya",
        "money laundering ki jaanch", "fir darj ho gayi hai",
        "aapka sim block hoga", "rbi ka notice aaya hai",
        "legal notice bheja jayega", "giraftari hogi", "turant transfer karo",
        "safe account mein paisa daalo", "yeh aapka aakhri mauka hai",
        "digital gireftari", "garreftari se bachna hai",
        "case band ho jayega payment ke baad", "aapki jaan khatrey mein hai",
        "aaj hi karo warna", "samay kam hai",
    ],
    # ─ Marathi ──────────────────────────────────────────────────────────────
    "mr": [
        "tुमच्यावर arrest warrant aahe", "cbi office madhun bolat aahe",
        "tुमcha account band hoil", "aata paishe transfer kara",
        "kunit sangoo naka", "court aadesh aahe",
        "narcotics case madhye naav aahe", "legal notice pathavla jeil",
        "tुमcha sim block hoil", "ek tasyaach aat kara",
        "sुrakshit account mdhye paisa taka", "giraftaritat jaaycha nasel tar",
        "aata karaych ahe", "veli sampat aahe",
    ],
    # ─ Tamil ────────────────────────────────────────────────────────────────
    "ta": [
        "ungalukku arrest warrant irukku", "cbi office irundhu pesugiren",
        "ungal account band aagidum", "ipave panam transfer pannunga",
        "yaarukkum sollaadhenga", "court order irukku",
        "narcotics case la ungal peru irukku", "sim block aagum",
        "legal notice varum", "oru mani neram mattumthan irukku",
        "safe account la panam podunga", "kaelvi ketkaadhenga",
    ],
}


def _build_lexicon() -> list[str]:
    """Flatten all phrases from BUILTIN_PHRASES into a single list."""
    phrases = []
    for lang_phrases in BUILTIN_PHRASES.values():
        phrases.extend(lang_phrases)
    # Deduplicate while preserving order
    seen = set()
    result = []
    for p in phrases:
        if p not in seen:
            seen.add(p)
            result.append(p)
    return result


def _save_lexicon(phrases: list[str]):
    LEXICON_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(LEXICON_PATH, "w", encoding="utf-8") as f:
        json.dump(phrases, f, ensure_ascii=False, indent=2)


def _load_lexicon() -> list[str]:
    if LEXICON_PATH.exists():
        with open(LEXICON_PATH, encoding="utf-8") as f:
            return json.load(f)
    phrases = _build_lexicon()
    _save_lexicon(phrases)
    return phrases


# ── TF-IDF Fast Path ───────────────────────────────────────────────────────────

_tfidf_vectorizer = None
_tfidf_matrix = None
_lexicon: list[str] = []


def _init_tfidf():
    global _tfidf_vectorizer, _tfidf_matrix, _lexicon
    if _tfidf_vectorizer is not None:
        return

    from sklearn.feature_extraction.text import TfidfVectorizer

    _lexicon = _load_lexicon()
    _tfidf_vectorizer = TfidfVectorizer(
        analyzer="char_wb", ngram_range=(2, 4), max_features=5000
    )
    _tfidf_matrix = _tfidf_vectorizer.fit_transform(_lexicon)
    print(f"[coercion_engine] TF-IDF vectoriser fitted on {len(_lexicon)} phrases ✓")


def _tfidf_score(text: str) -> tuple[float, list[str]]:
    """
    Compute max cosine similarity between input text and coercion lexicon.
    Returns (score in [0,1], top matching phrases).
    """
    from sklearn.metrics.pairwise import cosine_similarity

    _init_tfidf()
    vec = _tfidf_vectorizer.transform([text.lower()])
    sims = cosine_similarity(vec, _tfidf_matrix)[0]   # (N,)

    top_indices = np.argsort(sims)[::-1][:5]
    top_score   = float(sims[top_indices[0]]) if len(top_indices) > 0 else 0.0
    matched = [_lexicon[i] for i in top_indices if sims[i] > 0.05]

    return top_score, matched


# ── Groq / Llama 3 Slow Path ───────────────────────────────────────────────────

GROQ_SYSTEM_PROMPT = """You are a fraud detection AI for a UPI payment app.
Classify the following call transcript as COERCIVE or BENIGN.

COERCIVE: The caller is using threats, urgency, impersonation of authorities,
demands for immediate payment, or coercion to make the listener transfer money.

BENIGN: Normal conversation with no coercion, urgency, or payment pressure.

Respond ONLY with a JSON object: {"label": "COERCIVE"|"BENIGN", "reason": "<one sentence>"}"""


def _call_groq(text: str) -> dict:
    """Call Groq API with exponential backoff. Falls back to TF-IDF on failure."""
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        print("[coercion_engine] GROQ_API_KEY not set — using TF-IDF only")
        return None

    from groq import Groq

    client = Groq(api_key=api_key)
    for attempt in range(MAX_GROQ_RETRIES):
        try:
            response = client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[
                    {"role": "system", "content": GROQ_SYSTEM_PROMPT},
                    {"role": "user", "content": f"Transcript:\n{text[:2000]}"},
                ],
                temperature=0.1,
                max_tokens=100,
            )
            raw = response.choices[0].message.content.strip()
            # Parse JSON from response
            start = raw.find("{")
            end   = raw.rfind("}") + 1
            result = json.loads(raw[start:end])
            return result
        except Exception as exc:
            wait = 2 ** attempt
            print(f"[coercion_engine] Groq attempt {attempt+1} failed: {exc}. Retrying in {wait}s ...")
            time.sleep(wait)

    return None   # All retries exhausted


# ── Public API ─────────────────────────────────────────────────────────────────

def classify(text: str) -> dict:
    """
    Classify a transcript as COERCIVE or BENIGN.

    Two-path strategy:
      1. TF-IDF fast path  — returns immediately if score is clear-cut.
      2. Groq Llama 3      — used when TF-IDF score is uncertain.

    Args:
        text: Transcript string (lowercase preferred).

    Returns:
        {
            'label':           'COERCIVE' | 'BENIGN',
            'score':           float in [0, 1],
            'path':            'tfidf' | 'groq' | 'tfidf_fallback',
            'matched_phrases': list[str],
        }
    """
    tfidf_score, matched = _tfidf_score(text)

    # ── Clear COERCIVE ─────────────────────────────────────────────────────
    if tfidf_score >= TFIDF_THRESHOLD_COERCIVE:
        return {
            "label":           "COERCIVE",
            "score":           tfidf_score,
            "path":            "tfidf",
            "matched_phrases": matched,
        }

    # ── Clear BENIGN ───────────────────────────────────────────────────────
    if tfidf_score < TFIDF_THRESHOLD_UNCERTAIN:
        return {
            "label":           "BENIGN",
            "score":           tfidf_score,
            "path":            "tfidf",
            "matched_phrases": matched,
        }

    # ── Uncertain → escalate to Groq ──────────────────────────────────────
    groq_result = _call_groq(text)
    if groq_result:
        label = groq_result.get("label", "BENIGN").upper()
        if label not in ("COERCIVE", "BENIGN"):
            label = "BENIGN"
        return {
            "label":           label,
            "score":           tfidf_score,
            "path":            "groq",
            "matched_phrases": matched,
            "groq_reason":     groq_result.get("reason", ""),
        }

    # ── Groq failed → fall back to TF-IDF threshold ───────────────────────
    label = "COERCIVE" if tfidf_score >= TFIDF_THRESHOLD_UNCERTAIN else "BENIGN"
    return {
        "label":           label,
        "score":           tfidf_score,
        "path":            "tfidf_fallback",
        "matched_phrases": matched,
    }


async def classify_async(text: str) -> dict:
    """Async-safe wrapper — safe to call from asyncio.gather()."""
    return await asyncio.to_thread(classify, text)


# ── Self-test ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    _init_tfidf()

    test_cases = [
        ("CBI officer speaking. You are under digital arrest. Transfer money immediately to clear your name.", "COERCIVE"),
        ("Hi, I'd like to transfer ₹500 to my friend for dinner last night.", "BENIGN"),
        ("Aapka account band ho jayega. Abhi paisa transfer karo.", "COERCIVE"),
        ("Please send payment for the grocery order.", "BENIGN"),
        ("Warrant issued against you. Do not inform family. Time is running out.", "COERCIVE"),
    ]

    print("=" * 70)
    print("GuardPay AI — coercion_engine.py self-test")
    print("=" * 70)
    all_pass = True
    for text, expected in test_cases:
        result = classify(text)
        status = "✓" if result["label"] == expected else "✗"
        if result["label"] != expected:
            all_pass = False
        print(f"  {status}  [{result['path']:16}]  {result['label']:8}  "
              f"score={result['score']:.3f}  "
              f"'{text[:55]}...'")
    print()
    print("✓ All tests passed" if all_pass else "✗ Some tests failed (check Groq / thresholds)")
    print(f"  Lexicon size: {len(_lexicon)} phrases")
    print("=" * 70)
